import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { profile } from "@/data";
import "./globals.css";

// One monospace family for the whole site (IMPLEMENTATION.md §3).
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

// Placeholder origin — set to the deployed URL. Used by metadataBase / canonical / OG.
const SITE_URL = "https://ishaan.example.com";
const TITLE = `${profile.name} — ${profile.role}`;

// SEO metadata sourced from profile.json (IMPLEMENTATION.md §10). The OG/Twitter
// image is generated by src/app/opengraph-image.tsx and injected automatically.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: profile.bio,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: "/",
    siteName: profile.name,
    title: TITLE,
    description: profile.bio,
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: profile.bio,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jetbrainsMono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
